"""initial_migration

Revision ID: a91b3dad8869
Revises: 
Create Date: 2026-05-27 17:28:10.443441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a91b3dad8869'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('prompts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('prompt_set_id', sa.UUID(), nullable=False),
    sa.Column('conversation_family_id', sa.UUID(), nullable=True),
    sa.Column('prompt_text', sa.String(), nullable=False),
    sa.Column('tier', sa.Integer(), nullable=False),
    sa.Column('framing_category', sa.String(), nullable=False),
    sa.Column('domain', sa.String(), nullable=False),
    sa.Column('mymetadata', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prompts')
    op.drop_table('entities')
    # ### end Alembic commands ###
